1

In [1]:
import numpy as np

2

In [11]:
print(np.version.version)
np.show_config()

1.14.0
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nadia/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Users/Nadia/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nadia/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib'

3

In [12]:
a = np.zeros(10)

4

In [ ]:
print(a.nbytes)

5

In [14]:
python -c "import numpy as np; np.info(np.add)"

SyntaxError: invalid syntax (<ipython-input-14-113e43e8c33b>, line 1)

6

In [15]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7

In [16]:
a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8

In [17]:
print(np.flipud(a))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9

In [19]:
a = np.arange(9)
a = a.reshape([3, 3])
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10

In [20]:
a = np.array([1,2,0,0,4,0])
a[np.where(a != 0)]

array([1, 2, 4])

11

In [22]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12

In [25]:
a = np.random.random([3, 3, 3])
print(a)

[[[0.28339758 0.17772444 0.65390692]
  [0.47472391 0.34123302 0.13848587]
  [0.37601569 0.26560253 0.22373974]]

 [[0.84322694 0.81255377 0.08937506]
  [0.85825415 0.56064387 0.83896972]
  [0.96490888 0.75358683 0.02931904]]

 [[0.48021251 0.19854948 0.90698631]
  [0.82256857 0.19180765 0.32387818]
  [0.25034461 0.70938298 0.89760024]]]


13

In [26]:
a = np.random.random([10, 10])
print(a)
print("Min = " + str(a.min()))
print("Max = " + str(a.max()))

[[0.04950253 0.13894974 0.41090661 0.38208801 0.5572953  0.10636393
  0.95230779 0.58931213 0.20974651 0.60160514]
 [0.27255027 0.97714274 0.75785021 0.97581888 0.34133792 0.98882034
  0.48223222 0.52607887 0.36744124 0.27509896]
 [0.57630654 0.73703087 0.37215222 0.6661427  0.87947099 0.06482393
  0.52973081 0.3990177  0.33343583 0.38452547]
 [0.73278239 0.21839405 0.56202074 0.2632423  0.4958509  0.06711544
  0.76770378 0.64972474 0.32296118 0.38800047]
 [0.6803712  0.27323088 0.19757116 0.2631768  0.1011904  0.08770078
  0.51723229 0.43447404 0.24092241 0.06010749]
 [0.88557813 0.97377242 0.32762163 0.7025235  0.30141542 0.22009905
  0.87856201 0.44348744 0.47052925 0.77212174]
 [0.63367279 0.76267723 0.80642381 0.00137114 0.07776319 0.11230834
  0.40397124 0.21708883 0.9136372  0.37720836]
 [0.64844119 0.87276906 0.6607511  0.39746822 0.36286158 0.07211041
  0.83150033 0.20489918 0.01803476 0.72110301]
 [0.06936129 0.85182308 0.24111234 0.67446062 0.18838977 0.07014896
  0.92581431

14

In [ ]:
a = np.random.random(30)
print(a)
print("Mean = " + str(a.mean()))

15

In [32]:
a = np.zeros([4, 4])
a[:, 0], a[0], a[len(a)-1], a[:, len(a)-1] = 1, 1, 1, 1
print(a)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


16

In [38]:
a = np.random.random([3, 3])
b = np.zeros([len(a)+2, len(a)+2])
b[1:-1, 1:-1] = a
print(a)
print(b)

[[0.81187113 0.66291514 0.3263362 ]
 [0.68956631 0.39957388 0.9331224 ]
 [0.82004012 0.62159244 0.13490967]]
[[0.         0.         0.         0.         0.        ]
 [0.         0.81187113 0.66291514 0.3263362  0.        ]
 [0.         0.68956631 0.39957388 0.9331224  0.        ]
 [0.         0.82004012 0.62159244 0.13490967 0.        ]
 [0.         0.         0.         0.         0.        ]]


17

In [41]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


18

In [47]:
a = np.diag(np.arange(1,5), k = -1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19

In [51]:
a = np.zeros([8, 8], dtype = int)
a[::2,::2] = 1
a[1::2, 1::2] = 1
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


20

In [59]:
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


21

In [70]:
c = np.zeros([8, 8], dtype = int)
c[::2] = np.tile((0,1), 4)
c[1::2] = np.tile((1,0), 4)
print(c)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22

In [74]:
a = np.random.random([5, 5])
amax, amin = a.max(), a.min()
norm = (a - amin)/(amax - amin)
print(a)
print(norm)

[[0.38747418 0.67650743 0.12720552 0.41219273 0.50872846]
 [0.65219168 0.9521884  0.85653194 0.01634785 0.46567578]
 [0.85651758 0.85999721 0.47854965 0.95065772 0.59564515]
 [0.27884598 0.01965812 0.78004546 0.06256708 0.56122746]
 [0.65378841 0.99654521 0.77667759 0.80236058 0.34879355]]
[[0.37862408 0.67349659 0.1130973  0.40384202 0.50232803]
 [0.64868959 0.95474706 0.85715808 0.         0.45840557]
 [0.85714343 0.86069336 0.47153953 0.95318545 0.59100067]
 [0.26780131 0.00337714 0.77912636 0.04715299 0.55588765]
 [0.65031858 1.         0.77569046 0.80189231 0.33916201]]


23

In [75]:
rgba = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])

24

In [79]:
a = np.random.random([5, 3])
b = np.random.random([3, 2])
print(np.matmul(a, b))
#or np.dot(a, b)

[[0.50081668 0.44447296]
 [1.18886867 0.45730214]
 [0.65318358 0.20132162]
 [1.08195911 0.73101052]
 [0.65345888 0.77118705]]


25

In [84]:
a = np.arange(10)
print(a)
a[(a > 3) & (a < 8)] *= -1
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


26

In [160]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5), -1))

10
10


27

In [93]:
Z = np.ones(5, dtype = int)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

array([1., 1., 1., 1., 1.])

28

In [97]:
#print(np.array(0) / np.array(0))
#print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


29

In [103]:
a = np.random.uniform(-10,+10, 10)
print(a)
print (np.round(a))

[-0.5211583   0.87057492 -9.73689687  1.30963673 -0.70074735 -9.9789854
 -4.40976733 -4.76876662 -1.51829021 -0.77252295]
[ -1.   1. -10.   1.  -1. -10.  -4.  -5.  -2.  -1.]


30

In [105]:
a = np.arange(6)
b = np.arange(4, 10)
print(np.intersect1d(a, b))

[4 5]


31

In [127]:
settings = np.seterr(all = "ignore")
b = np.ones(1)
_ = np.seterr(**settings)
print(b/0)

[inf]


32

In [128]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


33

In [135]:
print(np.datetime64('today'))
print(np.datetime64('today') + np.timedelta64(1, 'D'))
print(np.datetime64('today') - np.timedelta64(1, 'D'))

2018-05-21
2018-05-22
2018-05-20


34

In [136]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

35

In [150]:
a = np.array(np.arange(1, 6), dtype = float)
b = np.array(np.arange(5, 10), dtype = float)
np.add(a, b, out = b)
np.divide(a, 2, out = a)
np.negative(a, out = a)
np.multiply(b, a, out = b)
print(b)

[ -3.  -8. -15. -24. -35.]


36

In [281]:
a = np.array([1.5, 2.7, 3.4])
print(np.modf(a)[1])
print(a//1)
print(np.floor(a))
print(np.ceil(a) - 1)
print(a.astype(int))

[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]
[1 2 3]


37

In [157]:
a = np.zeros([5, 5])
a[:] = np.tile(np.arange(5), 1)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38

In [163]:
def generator():
    a = 100*np.random.random(10)
    return np.round(a)
b = np.array(generator())
print(b)

[35. 60. 70. 43. 47. 52. 54. 73.  8. 99.]


39

In [165]:
a = np.linspace(0.0, 1.0, num = 11, endpoint = False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40

In [171]:
a = np.random.random(10)
print(np.sort(a))

[0.06145408 0.1049313  0.10616866 0.20874054 0.44474141 0.55848031
 0.61327123 0.89441551 0.90132209 0.93664161]


41

In [177]:
print(np.add.reduce([1, 2, 3]))

6


42

In [179]:
print(np.array_equal([1, 2, 3], [1, 2]))

False


43

In [181]:
a = np.ones(2)
a.setflags(write = False)
a[0] = 3
print(a)

ValueError: assignment destination is read-only

44

In [209]:
from math import sqrt
cart = np.array([generator(), generator()]).transpose()
print(cart)
polar = np.zeros([10, 2])
polar[:, 0] = np.sqrt((cart[:, 0]**2 + cart[:, 1]**2))
polar[:, 1] = np.arctan2(cart[:, 1], cart[:, 0])
print(polar)

[[57. 26.]
 [ 6. 68.]
 [45. 29.]
 [46. 26.]
 [61.  9.]
 [82. 49.]
 [ 7. 39.]
 [89. 69.]
 [93. 31.]
 [72. 78.]]
[[ 62.64982043   0.4279485 ]
 [ 68.26419266   1.48278895]
 [ 53.53503526   0.57245981]
 [ 52.83937925   0.51445131]
 [ 61.66036004   0.14648418]
 [ 95.52486587   0.53862417]
 [ 39.62322551   1.39320016]
 [112.61438629   0.65948554]
 [ 98.03060747   0.32175055]
 [106.15083608   0.82537685]]


45

In [210]:
a = np.random.random(10)
print(a)
a[np.argmax(a)] = 0
print(a)

[0.63200218 0.25228727 0.39018931 0.27246564 0.48515385 0.29963378
 0.182405   0.23767244 0.30233247 0.11251758]
[0.         0.25228727 0.39018931 0.27246564 0.48515385 0.29963378
 0.182405   0.23767244 0.30233247 0.11251758]


46

In [214]:
x = np.arange(0, 1.1, 0.1)
y = np.arange(0, 1.1, 0.1)
cx, cy = np.meshgrid(x, y)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


47

In [218]:
a = np.arange(21, 31)
b = np.arange(1, 11)
c = 1.0/np.subtract.outer(a, b)
print(c)

[[0.05       0.05263158 0.05555556 0.05882353 0.0625     0.06666667
  0.07142857 0.07692308 0.08333333 0.09090909]
 [0.04761905 0.05       0.05263158 0.05555556 0.05882353 0.0625
  0.06666667 0.07142857 0.07692308 0.08333333]
 [0.04545455 0.04761905 0.05       0.05263158 0.05555556 0.05882353
  0.0625     0.06666667 0.07142857 0.07692308]
 [0.04347826 0.04545455 0.04761905 0.05       0.05263158 0.05555556
  0.05882353 0.0625     0.06666667 0.07142857]
 [0.04166667 0.04347826 0.04545455 0.04761905 0.05       0.05263158
  0.05555556 0.05882353 0.0625     0.06666667]
 [0.04       0.04166667 0.04347826 0.04545455 0.04761905 0.05
  0.05263158 0.05555556 0.05882353 0.0625    ]
 [0.03846154 0.04       0.04166667 0.04347826 0.04545455 0.04761905
  0.05       0.05263158 0.05555556 0.05882353]
 [0.03703704 0.03846154 0.04       0.04166667 0.04347826 0.04545455
  0.04761905 0.05       0.05263158 0.05555556]
 [0.03571429 0.03703704 0.03846154 0.04       0.04166667 0.04347826
  0.04545455 0.0476190

48

In [225]:
ints = [np.iinfo(i) for i in (np.int8, np.int32, np.int64)]
print(ints)
floats = [np.finfo(i) for i in (np.float32, np.float64)]
print(floats)

[iinfo(min=-128, max=127, dtype=int8), iinfo(min=-2147483648, max=2147483647, dtype=int32), iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)]
[finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32), finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)]


49

In [226]:
np.set_printoptions(threshold=np.nan)

AttributeError: 'numpy.ndarray' object has no attribute 'set_printoptions'

50

In [234]:
a = 5
b = generator()
print(b)
print(b[np.argmin(abs(a-b[:]))])

[97. 83. 50. 12. 49. 85. 98. 83. 14. 50.]
12.0


51

52

In [237]:
a = np.random.random([100,2])
x,y = np.atleast_2d(a[:,0], a[:,1])
b = np.sqrt((x-x.transpose())**2 + (y-y.transpose())**2)
print(b)

[[0.         0.73441227 0.61534306 ... 0.0477998  0.3740737  0.21716029]
 [0.73441227 0.         0.98547986 ... 0.68694944 0.47795301 0.51778989]
 [0.61534306 0.98547986 0.         ... 0.62538071 0.89636604 0.67620587]
 ...
 [0.0477998  0.68694944 0.62538071 ... 0.         0.33274936 0.16945584]
 [0.3740737  0.47795301 0.89636604 ... 0.33274936 0.         0.2202819 ]
 [0.21716029 0.51778989 0.67620587 ... 0.16945584 0.2202819  0.        ]]


53

In [247]:
a = np.float32([1, 2, 3])
a = np.int32(a, copy = False)
print(a)

[1 2 3]


54

In [ ]:
a = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(a)

55

In [249]:
a = np.array([[1, 2], [3, 4]])
for i, x in np.ndenumerate(a):
    print(i, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


56

57

58

In [254]:
a = np.zeros([5, 5])
a[:] = np.arange(1, 6)
print(a)
a[:] = a[:] - mean(a)
print(a)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


59

In [267]:
n = 1
a = np.array([[1, 2, 7], [5, 8, 6], [9, 4, 3]])
a[np.argsort(a[:, n])]

array([[1, 2, 7],
       [9, 4, 3],
       [5, 8, 6]])

60

Vse OK


61

In [271]:
a = 10
b = np.array([[1, 2, 7], [5, 8, 6], [9, 4, 3]])
print(b.ravel()[np.argmin(abs(a-b[:]))])

9


62

In [295]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

[[0 1 1 1 1 2 2 1 0 0]
 [1 2 1 2 1 0 1 2 1 0]
 [2 2 1 0 2 0 2 2 0 2]]
False
